global:
  namespace: kavita
image:
  repository: ghcr.io/kareadita/kavita
  pullPolicy: IfNotPresent
  tag: 0.8.8@sha256:22c42f3cc83fb98b98a6d6336200b615faf2cfd2db22dab363136744efda1bb0
securityContext:
  container:
    readOnlyRootFilesystem: false
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0
service:
  main:
    ports:
      main:
        targetPort: 5000
        port: 10189
persistence:
  config:
    enabled: true
    mountPath: "/kavita/config"
  manga:
    enabled: true
    mountPath: "/manga"
  tmp:
    enabled: false

ingress:
  main:
    enabled: true
    required: true
    labels: {}
    annotations: {}
    ingressClassName: "traefik"
    hosts:
      - host: kavita.stenz.dev
          paths:
            - path: /
              pathType: Prefix
              overrideService:
                name: kavita
                port: 5000
    tls: 
      - secretName: spotify-stats-web-tls
        hosts:
          - kavita.stenz.dev
    integrations:
      certManager:
        enabled: true
        certificateIssuer: "letsencrypt-prod"
      traefik:
        enabled: true
        entrypoints:
          - websecure
        forceTLS: true
        middlewares: 
                - name: default-redirect-https@kubernetescrd
