apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: longhorn-system

helmCharts:
- name: longhorn
  releaseName: longhorn
  repo: https://charts.longhorn.io
  values: longhorn.values.yaml
  version: 1.7.1
