apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: seaweedfs

resources:
  - namespace.yaml

helmCharts:
  - name: seaweedfs
    releaseName: seaweedfs
    repo: oci://registry-1.docker.io/bitnamicharts
    valuesFile: seaweedfs.values.yaml
    version: 3.80.0