apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: seaweedfs

resources:
  - namespace.yaml

helmCharts:
  - name: seaweedfs
    releaseName: seaweedfs-release
    repo: https://charts.bitnami.com/bitnami
    valuesFile: seaweedfs.values.yaml
    version: 4.2.0