apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: seaweedfs
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Stenz123/k3s/
    path: seaweedfs
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default