apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vaultwarden

resources:
- postgres-cluster.yaml

helmCharts:
- name: vaultwarden
  releaseName: gissilabs/vaultwardenrs
  repo: https://gissilabs.github.io/charts/
  valuesFile: vaultwarden.values.yaml
  version: gissilabs/bitwardenrs/1.30.5
