apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: vaultwarden-postgres
  namespace: vaultwarden
spec:
  teamId: "acid"
  volume:
    size: 1Gi
  numberOfInstances: 2
  users:
    vaultwarden:  # database owner
    - superuser
    - createdb
    vaultwarden_user: []  # role for application vaultwarden
  databases:
    vaultwarden: vaultwarden  # dbname: owner
  preparedDatabases:
    bar: {}
  postgresql:
    version: "15"
