apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: vaultwarden-postgres
  namespace: vaultwarden
spec:
  teamId: "acid"
  volume:
    size: 1Gi
  numberOfInstances: 2
  users:
    vaultwarden:
      - superuser
      - createdb
    vaultwarden_user: []
  databases:
    vaultwarden: vaultwarden
  postgresql:
    version: "15"
  patroni:
    initdb:
      encoding: "UTF8"
      locale: "en_US.UTF-8"
      data-checksums: "true"
    pg_hba:
    - host all all 0.0.0.0/0 md5
    - hostssl all all 0.0.0.0/0 md5
    - host all all 10.42.0.0/16 md5
    - hostssl all all 10.42.0.0/16 md5

