apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vaultwarden
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/gissilabs/charts
    path: vaultwarden
    targetRevision: 1.30.5
    chart: gissilabs/vaultwarden
    helm:
      releaseName: gissilabs/vaultwarden
      valueFiles:
      - vaultwarden.values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
