database:
  type: postgresql
  wal: true
  url: "postgresql://vaultwarden:SmJDcWVsbDFxYlU1N29oclIyeWl0SUUzTDdoSHVBb3RBcmp0UmdIQjdjWktJR1MzUkVLZkxWV2hTalZnZ3ZMcg==@10.43.170.141:5432/vaultwarden"
vaultwarden:
  allowSignups: false
  verifySignup: false
  requireEmail: false
  allowInvitation: true
  showPasswordHint: false
  enableWebsockets: true
  enableWebVault: true
  enableSends: true
  orgCreationUsers: all

  admin:
    enabled: true
    disableAdminToken: false
  
service:
  type: ClusterIP
  httpPort: 80
  websocketPort: 3012
  externalTrafficPolicy: Cluster
  nodePorts:
    http: ""
    websocket: ""

ingressRoute:
  enabled: true
  newCRD: true
  host: "vaultwarden.stenz.dev"
  entrypoints:
    - websecure
  middlewares: {}
  tls:
    secretName: vaultwarden-tls
replicaCount: 1
