apiVersion: v1
kind: Secret
metadata:
  name: keycloak-credentials
type: Opaque
stringData:
  KEYCLOAK_ADMIN: "admin"
  KEYCLOAK_ADMIN_PASSWORD: "3Be]_6UItlq'L=IPjTbv::n+c&v-4[z]ok"
  POSTGRES_USER: "keycloak"
  POSTGRES_PASSWORD: ')%7yx9q^rwBlXkX(O8<W=:wzt&CV?5,V*H4tP3rr=Z;s>ZQ>2N{f}X]5bW6Kq}'
  POSTGRES_DB: "keycloak"