apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  name: keycloak-postgres
  namespace: keycloak
spec:
  teamId: "acid"
  volume:
    size: 1Gi
  numberOfInstances: 2
  users:
    keycloak:  # database owner
    - superuser
    - createdb
    keycloak_user: []  # role for application keycloak
  databases:
    keycloak: keycloak  # dbname: owner
  preparedDatabases:
    bar: {}
  postgresql:
    version: "15"
