apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wakapi

#resources:
#- postgres-cluster.yaml

helmCharts:
- name: postgres-operator-charts
  releaseName: postgres-operator
  repo: https://opensource.zalando.com/postgres-operator/charts/postgres-operator
  valuesFile: values.yml
  version: 1.11.0
