apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nextcloud

resources:
- nextcloud-pvc.yaml
- postgres-cluster.yaml

helmCharts:
- name: nextcloud
  releaseName: nextcloud
  repo: https://nextcloud.github.io/helm/
  valuesFile: nextcloud.values.yml
  version: 6.1.0
