apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd

resources:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.10.2/manifests/install.yaml
  #- argocd-deployment.yaml
  - argocd-ingress.yaml
  #- argocd-service.yaml

patches:
  - path: argocd-server-args-patch.yml
    target:
     group: apps
     version: v1
     kind: Deployment
     name: argocd-server
  - patch: |-
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: argocd-cmd-params-cm
      data:
        server.insecure: "true"
  - patch: |-
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: argocd-cm
      data:
        kustomize.buildOptions: --enable-helm
