apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: postgres-operator
  newName: registry.developers.crunchydata.com/crunchydata/postgres-operator
  newTag: ubi8-5.5.1-0

