apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: wakapi

resources:
- postgres-cluster.yaml

helmCharts:
- name: wakapi
  releaseName: wakapi
  repo: https://github.com/Stenz123/wakapi-helm-chart
  valuesFile: wakapi.values.yml
  version: 1.0.3
