persistence:
  enabled: false

image:
  tag: 2.11.1

wakapi_config:
  env: production
  db:
    dialect: postgres
    host: wakapi-postgres-rw.wakapi.svc.cluster.local
    port: 5432
    name: wakapi
    user: wakapi
    ssl: true
    password_secret:
      enabled: true
      name: wakapi-postgres-app
ingress:
  enabled: true
  annotations:
    traefik.ingress.kubernetes.io/router.tls: 'true'
    cert-manager.io/cluster-issuer: letsencrypt-prod
    traefik.ingress.kubernetes.io/router.middlewares: default-redirect-https@kubernetescrd
  hosts:
    - host: wakapi.stenz.dev
      paths:
        - '/'
  tls:
    - secretName: wakapi-tls
      hosts:
        - wakapi.stenz.dev
