apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: spotify-stats

resources:
- spotify-stats-server-deployment.yaml
- spotify-stats-web-deployment.yaml

helmCharts:
- name: mongodb
  releaseName: mongodb
  repository: "oci://registry-1.docker.io/bitnamicharts"
  version: 8.0.3
