apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: spotify-stats

resources:
- spotify-stats-server-deployment.yaml
- spotify-stats-web-deployment.yaml

helmCharts:
- name: mongodb
  releaseName: mongodb
  repo: https://charts.bitnami.com/bitnami
  #valueFile: mongo.values.yaml
  version: 8.0.3
