apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spotify-stats
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Stenz123/k3s/
    path: spotify-stats
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
