apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: letsencrypt
  namespace: argocd
spec: project: default
  source:
    repoURL: https://github.com/Stenz123/k3s/
    path: letsencrypt
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: default
