apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# https://github.com/cloudflare/origin-ca-issuer
# Install the Origin Ca issuer directly from the Repo. Otherwise it may come to complications
resources:
- cloudflare-token.yaml
- origin-issuer.yaml
- cert-stenz-dev.yaml
