apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/cert-manager/cert-manager/releases/download/v1.13.3/cert-manager.yaml
- https://raw.githubusercontent.com/cloudflare/origin-ca-issuer/v0.6.1/deploy/crds/cert-manager.k8s.cloudflare.com_originissuers.yaml
- origin-issuer.yaml
- cert-stenz-dev.yaml
- tls-store.yaml
